### ISSUE TITLE
Fix the sizing of text across all PDFs

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#113]
I think the best way to do this is to leave auto-sizing on for the text, but limit the height to the height of each text box to equivalent height of 12 pt text

**Comment by nonprofittechy** [comment]
Not necessarily urgent but will be important to improve the visual quality of the output.

**Comment by mnewsted** [comment]
Font size in AIW was addressed in earlier branch but I don't see it. Was it merged already @nonprofittechy ? If so, this can be closed.

**Comment by nonprofittechy** [comment]
Yes, merged!
