### ISSUE TITLE
propose merging question screens: (1) What is the name of the volunteer or person asking questions today?; (2) Is the preparer an attorney or accredited representative?

### ISSUE THREAD

**Issue by aidanielson** [IllinoisLegalAidOnline/docassemble-USCISApplications#117]
to reduce unnecessary standalone screen to ask the latter (the only question on that screen)

**Comment by nonprofittechy** [comment]
This was what I tried first but it didn't work with the object assignment question.

Maybe we could come up with a new variable for this that's not tied to the object. A standalone variable could solve this.

**Comment by aidanielson** [comment]
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/313aee90-6df3-443c-9633-5e8fe36630f1)

**Comment by nonprofittechy** [comment]
Please test this with choosing the preparer as an existing object. When I tested, the is_attorney variable got erased by the object assignment

**Comment by aidanielson** [comment]
I changed is attorney to a regular variable assuming it would avoid the issue entirely. But I'll test in a bit

Tony
________________________________

**Comment by nonprofittechy** [comment]
Oh that should work! I thought the screenshot showed the change
