### ISSUE TITLE
confirm necessity of successive "were you here before [date]" questions

### ISSUE THREAD

**Issue by aidanielson** [IllinoisLegalAidOnline/docassemble-USCISApplications#119]
seems like if you have proof of one, that might/would be proof viz. the later date.
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/352aec3b-2dd5-4a19-86ea-85c182043e04)

**Comment by nonprofittechy** [comment]
I believe Jane confirmed we do need both although temporal reasoning makes this confusing! We can follow-up with Jane one more time.
