### ISSUE TITLE
I-765 Page 4, part 3 items 1a-b and 2 not populating

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#122]
"I can read and understand English" or "Interpreter read to me in my language"

"The prepare prepared the application"

**Comment by nonprofittechy** [comment]
Should just be lining up the variables correctly (this is done right on the I-821?

**Comment by aidanielson** [comment]
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/ae96c68c-3a4e-4d92-9952-8e49aad25c18)
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/1bfdea4f-c031-4b50-b9f7-8cf016868191)
