### ISSUE TITLE
Page 7, part 6 1a-c: name is not populating sometimes or middle name is not populating

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#124]
Again not sure about this one, but there's a similar feedback on the I-821

**Comment by aidanielson** [comment]
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/59e7414a-02b2-40d3-ad29-418d52908c23)

**Comment by aidanielson** [comment]
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/11a7494f-382b-440c-b663-221cbf1e5209)
for I765

**Comment by aidanielson** [comment]
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/5ec8baed-ce00-45f6-8491-84d9be7c1f23)

**Comment by aidanielson** [comment]
for I821
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/b6dadcd9-9d58-49e3-8209-986845a8ff10)
