### ISSUE TITLE
Lived in other countries question - line up language with screener

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#129]

**Comment by mnewsted** [comment]
@nonprofittechy do we want to wait on rephrasing questions until we've restructured the other countries lived in / other countries citizenship? Should we fold this issue into that other one?

**Comment by mnewsted** [comment]
Here's the latest rewrite of this task incorporating language suggested by TRP.

Make screener "lived in other countries" language consistent - 
"Did applicant reside for more than 6 months in another country other than the country of which they are claiming TPS (i.e. Venezuela)?"
Then those countries can populate on the “residence” question on the 821
current interview language: After leaving your home country, were you in any other country for more than 6 months before arriving to the US?

**Comment by mnewsted** [comment]
Same as #154
