### ISSUE TITLE
limit additional travel docs to 3 total (get rid of NAME has more checkbox & following list gather)

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#130]

**Comment by aidanielson** [comment]
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/31de7c93-5e0e-4c17-a63e-00d015cbd8e7)

**Comment by aidanielson** [comment]
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/9cce3d4a-c6a3-4993-9c8e-0499747c88af)
