### ISSUE TITLE
Don't ask if someone lived in another country--they always have

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#132]
countries_of_residence - this is always true, default as birth country AND merge with screener question

**Comment by mnewsted** [comment]
Not sure what is requested here. Maybe it will resurface when we redo countries of residence questions?

**Comment by nonprofittechy** [comment]
I think on our Monday call we confirmed that this is incorrect, and the question does need to get asked after all.
