### ISSUE TITLE
I-765 Page 4, part 3 Salvadoran or Guatemalan national eligible for (some benefit)

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#138]
This is a checkbox we don't answer yet.

Probably need to ask this as a question, if they have any legal status in Guatemala including country of birth?

**Comment by nonprofittechy** [comment]
Need to ask Jane.

**Comment by mnewsted** [comment]
Matt is asking TRP. Update other issue with response

**Comment by mnewsted** [comment]
Jane said this does not need to be asked or filled in @aidanielson
