### ISSUE TITLE
do we want to implement date validation, like to ensure that dates aren't in the future or conflict with eachother

### ISSUE THREAD

**Issue by aidanielson** [IllinoisLegalAidOnline/docassemble-USCISApplications#143]
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/4a0a80bd-0281-42ef-8269-304e33f2f6be)

**Comment by nonprofittechy** [comment]
Note that we have been asked to add back in the "day" field at some point.

@mnewsted when you resolve #29 please check to see if this is still relevant (it might not be anymore)
