### ISSUE TITLE
addresses - suite, unit, etc., and fix to not show physical if mailing is physical address

### ISSUE THREAD

**Issue by aidanielson** [IllinoisLegalAidOnline/docassemble-USCISApplications#147]
Also - need to point out to Quinten that the apt/suite/floor pdf attachment block fields seem inconsistent between physical and mailing...
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/79eb16f4-f0ae-4554-b1a5-78b9eb3b570c)

**Comment by nonprofittechy** [comment]
The idea is to hide the mailing address fields if the two addresses are identical. It's not clear if this is needed but it does seem closer to the way a real person would fill in this field.

WOuld just need some mako if statements in the attachment block: `% if users[i].mailing_address == users[i].address:` e.g.

**Comment by mnewsted** [comment]
TRP said hiding mailing address if same as physical address is not needed.
