### ISSUE TITLE
If preparer is not an attorney, don't check the "does not extend" box on Part 5 7b

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#153]

**Comment by aidanielson** [comment]
fixed by changing line 2459 from 'Yes' to the below (as we were told if the preparer is an attorney, it will always be limited scope ['does not extend...']):
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/b4f67b95-fd1f-4b92-bd1f-5cc327910d22)
