### ISSUE TITLE
Rewrite this question: did applicant live in another coutnry before entering the US?

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#154]
Rewrite: 

> did applicant reside for more than 6 months in another country other than the country of which they are claiming TPS (i.e. Venezuela)?

**Comment by mnewsted** [comment]
In combined_application_questions.yml
id: countries resided in are there any
question: |
  Did Applicant **live** in another country before entering the U.S.?

Change to more specific language.
