### ISSUE TITLE
I-765 grouped feedback

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#157]
I-765

- [x] #158
- [x] #159
- [x] #160
- [x] #161
- [x] On page 7 of form I-821, there is no way to check the Y/N option for "Other countries";
- [x] #162

**Comment by aidanielson** [comment]
first item: the pdf field line is this: - "place_of_last_arrival": ${ users[i].city_of_entry }${ ', ' if showifdef('users[i].city_of_entry') else '' }${ users[i].state_of_entry }
