### ISSUE TITLE
Page 3 part 2, Item 23 -- always is coming out blank

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#158]

**Comment by nonprofittechy** [comment]
first item: the pdf field line is this: - "place_of_last_arrival": ${ users[i].city_of_entry }${ ', ' if showifdef('users[i].city_of_entry') else '' }${ users[i].state_of_entry }

**Comment by aidanielson** [comment]
works on my end...:
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/9136fe5e-d60d-4421-9b44-b26210a2b730)

![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/da9debfb-4154-4784-8078-0cb54b73a8ba)
