### ISSUE TITLE
I-765 It seems that no A#s are shown on the last page;

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#161]

**Comment by nonprofittechy** [comment]
Copy from the 821 attachment code that does work

**Comment by aidanielson** [comment]
I'm not seeing any error. The mako tag for PDF field 'A_2' is identical to the mako tag for the PDF field in the 821:
<img width="315" alt="image" src="https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/c4b68a7f-493d-48cd-97d3-59c66136d340">

![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/abfc228b-1939-4b27-af06-c67cc1c64da7)

![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/93ddb632-0451-40d9-8ed6-de538cae1096)

**Comment by aidanielson** [comment]
aaaaaaaaannnnnnddd it works on my test, both apps:

![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/cf8839d8-078b-465f-a474-e1877e330049)

![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/9f228f02-2b59-4b59-90ff-2d3be5a3e5af)
