### ISSUE TITLE
'How many?' question prompt in 'How many people are applying for work authorization at this station?' question causes hesitation/confusion

### ISSUE THREAD

**Issue by aidanielson** [IllinoisLegalAidOnline/docassemble-USCISApplications#164]
Each time I come across this very first question, I go cockeyed and have to re-read the top-line question text to realize, 'How many what...?' Perhaps it's just me, but I would suggest Matt takes a look and evaluates it.
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/981831fb-16bd-4829-a717-e4e962bdee86)

**Comment by mnewsted** [comment]
@aidanielson Since this program is for advocates, and they've used it hundreds of times now without mentioning anything, I'm okay with leaving it as is. There are ways it can be simplified or clarified, but I suspect by this point the preparers just blow by it and get to "How many?"

**Comment by aidanielson** [comment]
I'm likewise fine closing this out now that it's been specifically called out, considered, and affirmed.
