### ISSUE TITLE
ambiguous 'any child/any children' questions

### ISSUE THREAD

**Issue by aidanielson** [IllinoisLegalAidOnline/docassemble-USCISApplications#165]
These questions could cause confusion.

If there's only one parent (say, a mother) applying along with two other children, the second question might be confusing if the mother has another child (a third child) who is not applying in the interview session with the rest of the family (or who didn't come over at the same time, or some other reason).

If there's two parents, they may have children together or not, and it could be a mixed family. Both questions could be confusing - "Are you talking only about MY children?" Or: My fiance and I are applying together in this interview, and he's got his daughter (not mine) and I have my son (not his) and does the second question only ask if any of the two children were born outside of VZ, or only mine?"

![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/77826d6e-49c7-4cf7-885a-648c37f3eb4f)

**Comment by mnewsted** [comment]
@aidanielson I think this can be cleared up by changing the label of the 2nd question to "Were any of the children applying with you today born outside Venezuela?" That seems to be what the screener is interested in, no?

Also, it is fairly common, in ILAO programs at least, to use "children" to include 1 or many children. At least until the # of children is known. Even then, it's often easier to use "children" throughout.

**Comment by mnewsted** [comment]
@nonprofittechy can we do this? we'll add it as you see fit. Thanks!
