### ISSUE TITLE
Change "birth names of users[i]'s parents" to open ended text fields, not comboboxes

### ISSUE THREAD

**Issue by aidanielson** [IllinoisLegalAidOnline/docassemble-USCISApplications#192]
**Spreadsheet Question/Issue:** Parents 1st name and both last names gets populated in parents info but not second first name.  (The program does not ask for middle name). Names need to be accurate - should have the option to add them exactly as they appear on someone's ID docs (see screenshot 3)

[and line 17 from spreadsheet]

Can we get an unknown check box for father or mothers name. (often times a person does not know their father's name). Or instruct folks to write “unknown” (see screenshot 4)

**Questions/s Follow-up for TRP:** 

**Spreadsheet Comments:** Make names text boxes. Add checkbox for unknown for each one - put Unknown in form.

dropdown we're using may cutoff part of the name they entered. Where do we put the middle name? Have 'unknown' populate in form if one or both parents is unknown. Maybe checkboxes next to mother and father saying, e.g., 'Mother's name is unknown'

![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/63eafa76-6eb6-4944-8468-c393485c449f)

**Comment by nonprofittechy** [comment]
Answer: just provide some text boxes and instruct the person to enter exactly as on the ID, or enter "unknown"

**Comment by nonprofittechy** [comment]
Is there a problem where one of the form asks for "first middle last" and one just "first last"? If so--how do we decide which name goes in which field?
