### ISSUE TITLE
Looks like travel addendum is not populating properly. Addendum with others countries is coming out but not traditional countries. (see screenshot 7)

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#196]

**Comment by mnewsted** [comment]
Oswaldo said "Yes, sometimes "See Addendum" wasn't being generated. It seems that for the most part, it was being generated but there would be random application that wouldn't include them. We can keep an eye out for it, and let you know if there are any triggers or if maybe it was user error from before. "
