### ISSUE TITLE
Update the setup.py to contain the specific dependencies needed to install on a brand new server

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#211]
@mnewsted, this means your ILAO framework, e.g., needs to be on PyPI--is it?

**Comment by nonprofittechy** [comment]
Also, add a login step (to the admin account?) to the .feature file so we can see the contents of error messages

**Comment by nonprofittechy** [comment]
Login username/password should be in the action output

**Comment by ll-jgraszer** [comment]
The updates have been made and now the Docker has the DA working and ALKiln is running the tests. There are other issues happening within the tests from this automated setup that I thought I had fixed when I was manually testing using ALKiln in the playground from the existing running server. I'm testing to see if adding triggers fixes the issues I was seeing like signatures not being able to continue.

**Comment by ll-jgraszer** [comment]
While I have the ALKiln running within GitHub Actions it's still running into an issue with the user[0].address block of questions not filling them out to continue. At the same time I do have all of the tests passing on the ALKiln in the playground. I've put a message in the alkiln testing channel hopefully get some idea of what to try here next to hopefully get the automated testing working.
