### ISSUE TITLE
Add Haiti as an option for country of origin and include generated form "Haiti TPS Addendum - Child Nationality" 

### ISSUE THREAD

**Issue by KelizaMcGuire** [IllinoisLegalAidOnline/docassemble-USCISApplications#217]
The option for Haiti will use the same addenda as Venezuela except for child nationality which has its own form.

Note: We are waiting for proof of nationality inputs other than birth certificate from TRP.

**Comment by KelizaMcGuire** [comment]
> The option for Haiti will use the same addenda as Venezuela except for child nationality which has its own form.
> 
> Note: We are waiting for proof of nationality inputs other than birth certificate from TRP.

Proof of nationality options will be a birth certificate and a text field where the user can list other docs.

**Comment by ll-jgraszer** [comment]
Added the new fields to the interview and presented them this way:
![Image](https://github.com/user-attachments/assets/81b194b5-f5d8-482e-937c-7166c554bdad)

If they have other forms of proof of parents nationality we can add those later.
