### ISSUE TITLE
Add new version of I-765 for document generation

### ISSUE THREAD

**Issue by KelizaMcGuire** [IllinoisLegalAidOnline/docassemble-USCISApplications#222]
There is a new version of the I-765 document that will need to be used starting 10/28/2024

[i-765_updated new version 8.28.24.pdf](https://github.com/user-attachments/files/17192099/i-765_updated.new.version.8.28.24.pdf)

**Comment by ll-jgraszer** [comment]
Got the updated 8/28/24 version of the i-765 form field names and added the checkboxes for Q30:

[i-765_flattened_MN_updated_082824.pdf](https://github.com/user-attachments/files/17249184/i-765_flattened_MN_updated_082824.pdf)
