### ISSUE TITLE
I-765 - 27. Eligibility Category: Make drop-down menu with 4 options

### ISSUE THREAD

**Issue by KelizaMcGuire** [IllinoisLegalAidOnline/docassemble-USCISApplications#223]
The provided uptions for the drop-down menu should be as follows in the screenshot below, however, the option for Asylum should be (c)08 as the filled out example provided by TRP shows.

<img width="452" alt="Screenshot 2024-09-30 at 10 42 44 AM" src="https://github.com/user-attachments/assets/764b31a5-9f08-4241-aadf-2d3646e4b39d">
<img width="297" alt="Screenshot 2024-09-30 at 10 45 40 AM" src="https://github.com/user-attachments/assets/a2e82810-7f3a-409d-b438-a4c48daf7efa">
<img width="289" alt="Screenshot 2024-09-30 at 11 11 51 AM" src="https://github.com/user-attachments/assets/9f191f58-06bd-4e80-a781-ddfeb622c8c6">

**Comment by ll-jgraszer** [comment]
TRP got back to us on the workflow for this one we're going to add the options for EAD:

``` 
- EAD  based on TPS
- EAD based on asylum
- EAD based on parole
- EAD based on order of supervision
```

This will modify the look and feel of the current kind of application screen we're currently using:
![Image](https://github.com/user-attachments/assets/b087785f-9883-4c87-92f9-d58034f28900)
