### ISSUE TITLE
I-765 - 30. If filing for asylum, make answer required and documentation required

### ISSUE THREAD

**Issue by KelizaMcGuire** [IllinoisLegalAidOnline/docassemble-USCISApplications#224]
If answering with Asylum - (C)(08) to question 27. Eligibility Category requires question 30 to be answered and should include the list of required documentation below.

A redacted fully filled-out form using Asylum - (C)(08) as an example is available in the TRP Google Drive and Sharepoint folder.

[EAD Application Checklist for Category C08.docx](https://github.com/user-attachments/files/17192279/EAD.Application.Checklist.for.Category.C08.docx)

<img width="297" alt="Screenshot 2024-09-30 at 10 45 40 AM" src="https://github.com/user-attachments/assets/1f535d18-de3d-4385-943e-5de1cde50ccf">
<img width="452" alt="Screenshot 2024-09-30 at 10 42 44 AM" src="https://github.com/user-attachments/assets/fa90f6d7-6553-4247-8002-285fca15fa25">
<img width="289" alt="Screenshot 2024-09-30 at 11 11 51 AM" src="https://github.com/user-attachments/assets/6e1b865c-d3c7-4881-8372-d9bdb92d1e54">

**Comment by ll-jgraszer** [comment]
This question will only come up for the `EAD based on asylum` option from application kind.
