### ISSUE TITLE
Add a "region" selector question so that TRP can track Easy Forms use across regions

### ISSUE THREAD

**Issue by KelizaMcGuire** [IllinoisLegalAidOnline/docassemble-USCISApplications#244]
The region selector should be included in each interview run and provide a way for internal tracking of Easy Forms used by partners/workshops across regions.

The region options should be:

- Chicago
- Northern Illinois
- Western Suburbs
- Central & Downstate Illinois

**Comment by ll-jgraszer** [comment]
This was handled with the EAD updates.
