### ISSUE TITLE
Whenever a list is displayed in a subquestion, we should format it in a bullet list or comma_and_list. Example id: countries resided in.

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#33]

**Comment by mnewsted** [comment]
I asked for feedback. They will provide as needed.

**Comment by mnewsted** [comment]
I added this to the questions I saw in the TPS path. Will check in EAD path, then will push in AIWEligibility branch.

**Comment by mnewsted** [comment]
I believed I've updated all the questions I came across. Pushed to the AIWEligibility branch.
