### ISSUE TITLE
Interview & documents feedback

### ISSUE THREAD

**Issue by mnewsted** [IllinoisLegalAidOnline/docassemble-USCISApplications#35]
I-765 
Part 2
- [ ] 10 Gender (empty)
- [ ] 12 (empty)
- [ ] 13a (empty)
- [ ] 18ab countries of citizenship (empty)
- [ ] 19ab city & state/province of birth both blank (were these asked?)
- [ ] 21c travel doc num (empty)
- [ ] 21d passport country (empty)
- [ ] 22 date of last arrival (empty)
- [ ] 24 immigration status at last arrival (empty)

Part 3
- [ ] 1b language (empty)
- [ ] 3 applicant daytime phone (empty not asked)
- [ ] 4 applicant mobile number (empty not asked)
- [ ] 5 applicant email (empty not asked)

Part 4
- [ ] 2 Interpreter organization (blank) - if we don't use this mb we don't need to ask in interview?
- [ ] 3abcdefgh Interp mailing address (blank)
- [ ] 4 interp daytime phone (empty not asked)
- [ ] 5 interp mobile number (empty not asked)
- [ ] 6 interp email (empty not asked)

Part 5
- [ ] Preparer contact info
- [ ] 456 blank
- [ ] 7b main checkbox isn't checked (but "does not extend" subcheckbox is)

**Comment by nonprofittechy** [comment]
Are these still empty with the new PDF/different browser?

**Comment by mnewsted** [comment]
Yes they were still empty even when I looked at the doc in Firefox. The other fields were filled in.

I was going to test again with multiple applicants in a family. Should I do that now or wait?

**Comment by nonprofittechy** [comment]
Can you try regenerating with the newest PDF that I installed around 4:30 ? You should be able to use an answer set to jump right to the PDF generation step.

**Comment by mnewsted** [comment]
I just re-assembled the docs (made changes to have you evers, entered explanations, and downloaded) and it is still looking the same in Chrome and in Firefox. Not sure if I need to start the interview over again.

**Comment by nonprofittechy** [comment]
I wouldn't expect you to have to start over. But I ran the interview through in Firefox and things are filling in correctly for me...definitely not 50+ missing fields 

> Interview
> 
>     * [ ]  id: intro_main - change id to welcome
> 
>     * [ ]  id: intro_main - Overview steps/sections in subquestion vary from left nav. Maybe sections got messed up. Is Review your answers used?
> 
>     * [x]  id: people - not using date datatype for birthdate?
> 
>     * [ ]  id: have you been known by a different name again - show So far you entered: name, name, and name.
> 
>     * [ ]   - is there a maximum?
> 
>     * [ ]  id: review_intial_user_list - subquestion - On the next screenS, we'll review the limited scope retainer.
> 
>     * [ ]  id: alternate birthdates there is another - limit?
> 
>     * [ ]  id: alternate birthdates there is another - format So far you entered...
> 
>     * [x]  id: your address - asks this instead of more detailed info for other applicants (users[1], etc.)
> 
>     * [x]  id: mailing address - asks this instead of more detailed info for other applicants (users[1], etc.)
> 
>     * [x]  id: U.S. entry info and travel documents - DT - should we explain what this is (add it to the label?)
> 
> 
> DOCS PRODUCED
> 
>     * [ ]  retainer - date text can be moved down closer to line (Eng and Spa)

Not so sure--this was really hard to get to fit on one page. 

>     * [ ]  AIW - more than 1 Race category checked (Caucasian/Latino and another) - is this okay since Latino is tracked separately?

The forms aren't consistent with one another.

>     * [ ]  AIW - change checkbox appearance to Cross
> 
>     * [ ]  AIW - height/feet/inches and weight/pounds are empty

I don't think we're intended to complete both, just one of the two. They suggested only using centimeters/kilos.

>     * [x]  I-821 - many fields not filled in for users[0] (this might be a browser issue)
> 
>     * [x]  I-821 A-Number - interview should limit to 9 chars
> 
>     * [ ]  I-821 I94 arrival number - interview should limt to 11 chars
> 
>     * [x]  I-821 - fields not filled in (at least on my PC). Some of these might not be needed per customer.
> 
> 
> Part 2
> 
>     * [ ]  5 checkbox (empty)
> 
>     * [ ]  11a other dob (empty)
> 
>     * [ ]  11b other dob (empty)
> 
>     * [ ]  12 gender (empty)
> 
>     * [ ]  13 city/town/village of birth (empty)
> 
>     * [ ]  16abcd countries of citizenship (empty)
> 
>     * [ ]  19 date of last entry into US (empty)
> 
>     * [ ]  24 date of authorized stay period (i think I entered a text field in interview) (empty)
> 
>     * [ ]  30 passport expiration # (empty)
> 
>     * [ ]  32 were you ever in immigration proceedings y/n both empty - should be Y for this applicant (empty)
> 
> 
> Part 3
> 
>     * [ ]  2 Race (empty)
> 
>     * [ ]  3 height inches (though maybe it was zero) (empty)
> 
> 
> Part 7
> 
>     * [ ]  1a national of what country (empty)
> 
>     * [ ]  1c other countries Y/N checkboxes (empty) - should be Yes
> 
>     * [ ]  2 - "See addendum" is helpful, but if it covers more answers maybe it should say See addendum for 2-7)

Good thought--we mirrored the form that we got from the client here though.

> 
>     * [ ]  3ab (empty)
> 
>     * [ ]  4 (empty)
> 
>     * [ ]  5 (empty)
> 
>     * [ ]  6 (empty)
> 
>     * [ ]  7 (empty)

Here, for 3a-7, I think we really should just remove the questions in the interview. This apparently handles almost every person and would greatly speed up the workflow if that's true. 

Alternatively, we could skip these questions if the user has the addendum for transit through central america checked.

>     * [ ]  20d No & IDK are both checked when IDK selected
> 
> 
> Part 8
> 
>     * [ ]  2 checkbox and blank for preparer these were empty, do we fill them in?
> 
>     * [ ]  3 applicant daytime phone (empty not asked)
> 
>     * [ ]  4 applicant mobile number (empty not asked)
> 
>     * [ ]  5 applicant email (empty not asked)

Phone and email are intended to be blank.

> 
> Part 9
> 
>     * [ ]  2 Interpreter organization (blank) - if we don't use this mb we don't need to ask in interview?

We don't ask this anymore in the most recent version.

> 
>     * [ ]  3 interp daytime phone (empty not asked)
> 
>     * [ ]  4 interp mobile number (empty not asked)
> 
>     * [ ]  5 interp email (empty not asked)

These are intentionally not asked.

> 
> 
> I-765 Part 2
> 
>     * [ ]  10 Gender (empty)
> 
>     * [ ]  12 (empty)
> 
>     * [ ]  13a (empty)
> 
>     * [ ]  18ab countries of citizenship (empty)
> 
>     * [ ]  19ab city & state/province of birth both blank (were these asked?)
> 
>     * [ ]  21c travel doc num (empty)
> 
>     * [ ]  21d passport country (empty)
> 
>     * [ ]  22 date of last arrival (empty)
> 
>     * [ ]  24 immigration status at last arrival (empty)
> 
> 
> Part 3
> 
>     * [ ]  1b language (empty)
> 
>     * [ ]  3 applicant daytime phone (empty not asked)
> 
>     * [ ]  4 applicant mobile number (empty not asked)
> 
>     * [ ]  5 applicant email (empty not asked)

Phone/email aren't intended to be asked

> 
> Part 4
> 
>     * [ ]  2 Interpreter organization (blank) - if we don't use this mb we don't need to ask in interview?

No longer asked 

>     * [ ]  3abcdefgh Interp mailing address (blank)
> 
>     * [ ]  4 interp daytime phone (empty not asked)
> 
>     * [ ]  5 interp mobile number (empty not asked)
> 
>     * [ ]  6 interp email (empty not asked)

email/phone should be blank.

> 
> Part 5
> 
>     * [ ]  Preparer contact info
> 
>     * [ ]  456 blank
> 
>     * [ ]  7b main checkbox isn't checked (but "does not extend" subcheckbox is)
> 
> 
> TPS Eligibility review forms
> 
>     * [ ]  Assembled 2 TPS eligibility review forms - Is there supposed to be an EAD eligibility review form?

No

>     * [ ]  TPS eligibility review form - addenda list has extra blank bullets between each legit item
> 
>     * [ ]  Supervisor notes - Does the supervisor name need to appear on the doc?
> 
>     * [ ]  Arrest history - are we using that 1-row table (date, location, charge, outcome)?
> 
> 
> Addenda
> 
>     * [ ]  I-821 addendum for have you evers - uses users[0] explanations instead of users[1] - this could have been an assembly glitch that was addressed
