### ISSUE TITLE
Additional issues

### ISSUE THREAD

**Issue by mnewsted** [IllinoisLegalAidOnline/docassemble-USCISApplications#39]
I checked #35 and tried to avoid any duplicate entries. If there are things in both places, it means I was still having trouble with them on this run through even if they were checked as resolved in the other issue.

Interview
- [x] #55
- [x] #56
- [x] will there be a review page? not sure what plans were though I still see a section.

AIW (thanks for updating checkboxes to Cross, at least when I view in Firefox. Chrome still shows them as checks?)
- [x] #41

I-821
- [x] #42
- [x] #43
- [x] #44
- [x] #45
- [x] #46
- [x] #47
- [x] #48
- [x] #49
- [x] #50
- [x] #51
- [x] #52
- [x] #53

I-765
- [x] #54

**Comment by nonprofittechy** [comment]
All items moved to separate issues
