### ISSUE TITLE
id: have you been known by a different name again - show So far you entered: name, name, and name.

### ISSUE THREAD

**Issue by nonprofittechy** [IllinoisLegalAidOnline/docassemble-USCISApplications#57]

**Comment by nonprofittechy** [comment]
Is there a maxmimum number of names?

**Comment by mnewsted** [comment]
I-821 allows for up to 2 aliases. I-765 allows for up to 3.

Maybe we cap program at 3 and add the 3rd name to an addendum for the I-821? Or we can find out if a max of 2 is sufficient.

**Comment by nonprofittechy** [comment]
I think: cap names at 2 with a warning that you can fit one more on the I-765 but you need to add to addendum manually for now.

**Comment by nonprofittechy** [comment]
```
code: |
  if len(users[i].aliases.complete_elements()) >= 2:
    users[i].aliases.there_is_another = False
```

This needs to be after the normal "there is another" question. notice it's only defining the False value; it won't set the value unless the condition is True, so you get the normal question block to run instead when < 2.

**Comment by mnewsted** [comment]
Started working on this, but there are some al_baseline questions that are conflicting with how we were going to set up the cap.

**Comment by mnewsted** [comment]
@nonprofittechy I forgot to discuss this today. Did we want to look at the upstream changes?

**Comment by nonprofittechy** [comment]
Oh, sure. If I remember right, the issue was about having to customize both users[0] and users[I]?

**Comment by mnewsted** [comment]
Yes, there was something peculiar going on. Maybe it can be addressed if we modify both users[0] and users[i]. Will docassemble pick a specific question that defines users[0] even if there is a later question that asks for the same attributes for users[i]?

**Comment by mnewsted** [comment]
Not capped at 2. Can we look at this @nonprofittechy

**Comment by mnewsted** [comment]
@nonprofittechy i was planning to talk with you about this on friday but we ran out of time. i thought this might involve upstream question issues. basically, i think the goal is to cap the aliases at 2 in the interview. please let me know if you have code suggestions or if you would like to discuss. thanks!

**Comment by mnewsted** [comment]
ALSO close div tag on tps_screening_questions
