### ISSUE TITLE
Issues from 2/20 meeting with TRP

### ISSUE THREAD

**Issue by mnewsted** [IllinoisLegalAidOnline/docassemble-USCISApplications#79]
- [x] #84
- [x] #85
- [x] #80
- [x] #125
- [x] #81
- [x] #82
- [x] #126
- [x] #127
- [x] #128
- [x] #83
- [x] #129
- [x] #130
- [x] #86
- [x] have you evers - 20c and 20d are conditional - use show if as needed
- [x] #131
- [x] #132
- [x] #87
- [x] #88

 (See #18 , this feedback moved there) I-821 page 2 - Countries of residence (before entering US) and Countries of Citizenship/Nationality - Impose hard limit of 4, need to break up answers into separate numbered form fields

**Comment by nonprofittechy** [comment]
All issues were migrated; closing this tracking issue.
