### ISSUE TITLE
Still have "When, Where, and With Whom" if applicant's children entered US separately from applicant (in screener)

### ISSUE THREAD

**Issue by aidanielson** [IllinoisLegalAidOnline/docassemble-USCISApplications#90]
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/0c8e0ee8-abe3-464a-85f5-7913bf851c86)

**Comment by mnewsted** [comment]
Is this issue, just remove it if not used in forms/screening process? Or do we need to adjust logic? Where is it used?

**Comment by nonprofittechy** [comment]
@aidanielson can you explain more about what needs to change here?

**Comment by aidanielson** [comment]
A few meetings ago, I recall Jane or Katherine or someone else at TRP say strongly that this should be broken out into individual questions and not asked in a lump. We need to revisit this with TRP at the next check in

**Comment by aidanielson** [comment]
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/1c0e5989-7c45-4bb6-ab80-6f4702d5b75e)

**Comment by mnewsted** [comment]
TRP said this is fine as is. No changes needed.
