### ISSUE TITLE
Venezuela and Haiti, etc. are not at top of countries drop-down and the wording of "First Country you are a citizen of" could be improved, as it lacks the birth country default or any help text or suggestion, or (if any)

### ISSUE THREAD

**Issue by aidanielson** [IllinoisLegalAidOnline/docassemble-USCISApplications#91]
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/a262d38c-064e-47d0-abec-a2be09ffc578)

**Comment by mnewsted** [comment]
See #81 and #82 

Should default of 1st country you are citizen of be birth country?
